FROM python:3.12.11-slim

RUN apt-get update && apt-get install -y \
build-essential curl \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Use uv for faster package management
RUN pip install uv 

COPY ./src /app/src
# requirements
COPY requirements.txt .

# with uv
RUN uv pip install --system --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "src.api.fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]


