name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest 
      
      - name: Run tests
        run:  TEST_ENV=1 PYTHONPATH=. pytest -q
  
  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      - name: Build FastAPI image
        run: docker build -f Dockerfile.fastapi -t ci-fastapi .
      
      - name: Build Streamlit image
        run: docker build -f Dockerfile.streamlit -t ci-streamlit .

